spring:
  datasource:
    url: jdbc:mysql://3.25.201.88:3306/classicmodels
    username: teamuser
    password: team123

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

  thymeleaf:
    cache: false